# Generated by Django 3.2 on 2021-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('fb_link', models.URLField(max_length=300)),
                ('twitter_link', models.URLField(max_length=300)),
                ('instagram_link', models.URLField(max_length=300)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
    ]
