# Generated by Django 3.2 on 2021-04-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
