# Generated by Django 3.2 on 2021-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_of_the_week',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
