# Generated by Django 3.2 on 2021-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='tags',
            field=models.CharField(max_length=50),
        ),
    ]
