# Generated by Django 3.2 on 2021-04-20 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_reviews', '0002_eventreview_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreview',
            name='dislikes',
            field=models.ManyToManyField(default=None, related_name='event_review_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='funny',
            field=models.ManyToManyField(default=None, related_name='event_review_funny', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='event_review_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
