# Generated by Django 3.2 on 2021-04-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reviews', '0003_auto_20210420_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreview',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
