# Generated by Django 3.2 on 2021-04-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_reviews', '0005_bar_review_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar_review',
            name='likes',
        ),
    ]
