# Generated by Django 3.2 on 2021-04-20 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bar_reviews', '0006_remove_bar_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar_review',
            name='likes',
            field=models.ManyToManyField(related_name='bar_review_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
