# Generated by Django 3.2 on 2021-04-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_reviews', '0010_auto_20210420_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_review',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
