# Generated by Django 3.2 on 2021-04-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_reviews', '0011_alter_bar_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_review',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
