# Generated by Django 3.2 on 2021-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_website'),
        ('bars', '0002_alter_bar_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='events',
            field=models.ManyToManyField(related_name='bars', to='events.Event'),
        ),
    ]
